### ISSUE TITLE
Error - java.lang.OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by hmf** [msigwart/fakeload#11]
I got this error when asking for a Disk-out load of 2 GB. Apparently their is a [maximum size](https://www.baeldung.com/java-arrays-max-size) for the arrays. I think this can be corrected by creating smaller arrays and making multiple writes.  

Interestingly I did not get this when I did a disk read load simulation. I suspect that it is because the file size is 1.1G, which leads me to wonder if the 2G read load is executed correctly.

I have added the stack trace below in case it is useful.

HTHs.

```java
java.util.concurrent.CompletionException: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.OutOfMemoryError: Requested array size exceeds VM limit
	at com.martensigwart.fakeload.DiskOutputSimulator.simulateLoad(DiskOutputSimulator.java:41)
	at com.martensigwart.fakeload.AbstractLoadSimulator.run(AbstractLoadSimulator.java:102)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 3 more
```

**Comment by hmf** [comment]
Just a note on this. I see that in the [code](https://github.com/msigwart/fakeload/blob/d177b61d53a6e91bb55eae5cd6fe07d1c95534aa/src/main/java/com/martensigwart/fakeload/DiskInputSimulator.java#L37) a cast and check are made. The cast may not be correct for very large files. I also don't know if the Maven version has this test. If it does then the check is also failing, but I don't know why.
