### ISSUE TITLE
"Temp file does not exist" 

### ISSUE THREAD

**Issue by piwa** [msigwart/fakeload#3]
It seems that the loader also needs a temp file even when I only would like to fake the CPU load. After I created the file the loader worked. Is the file really also required for a CPU fake load?

```
FakeLoad fakeload = new FakeLoadBuilder()
      .lasting(20000, TimeUnit.MILLISECONDS)
      .withCpu(60)
      .build();

FakeLoadExecutor executor = FakeLoadExecutors.newDefaultExecutor();
executor.execute(fakeload);
```

```
2017-09-05 15:02:51.706 ERROR 38460 --- [cTaskExecutor-1] c.m.fakeload.FakeLoadExecutors           : File /var/folders/98/r5_1dy6d2y3866thdzrwtq2h0000gn/T//input.tmp used for simulating disk input does not exist. (The file should be at least twice as big as available RAM to prevent caching)
2017-09-05 15:02:51.714 ERROR 38460 --- [cTaskExecutor-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void at.ac.tuwien.infosys.viepepcbackendservice.ServiceExecutor.execute(int,java.lang.String,java.lang.String,java.lang.String,java.lang.String)'.

java.lang.IllegalArgumentException: java.io.FileNotFoundException: /var/folders/98/r5_1dy6d2y3866thdzrwtq2h0000gn/T/input.tmp (No such file or directory)
	at com.martensigwart.fakeload.FakeLoadExecutors.newDefaultExecutor(FakeLoadExecutors.java:74) ~[fakeload-0.3.0.jar:na]
	at at.ac.tuwien.infosys.viepepcbackendservice.ServiceExecutor.execute(ServiceExecutor.java:63) ~[classes/:na]
	at at.ac.tuwien.infosys.viepepcbackendservice.ServiceExecutor$$FastClassBySpringCGLIB$$68b89145.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: java.io.FileNotFoundException: /var/folders/98/r5_1dy6d2y3866thdzrwtq2h0000gn/T/input.tmp (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_112]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_112]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_112]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124) ~[na:1.8.0_112]
	at com.martensigwart.fakeload.RandomAccessDiskInputSimulator.<init>(RandomAccessDiskInputSimulator.java:25) ~[fakeload-0.3.0.jar:na]
	at com.martensigwart.fakeload.FakeLoadExecutors.newDefaultExecutor(FakeLoadExecutors.java:39) ~[fakeload-0.3.0.jar:na]
	... 8 common frames omitted
```

**Comment by msigwart** [comment]
Issue was resolved in version 0.3.1, input.tmp file is now only required when disk input is being simulated.
